QBShared = QBShared or {}
QBShared.Vehicles = {
	--- Compacts
	['asbo'] = {
		['name'] = 'Asbo',
		['brand'] = 'Maxwell',
		['model'] = 'asbo',
		['price'] = 4000,
		['category'] = 'compacts',
		['hash'] = `asbo`,
		['shop'] = 'pdm',
	},
	['mb6'] = {
		['name'] = 'Maybach',
		['brand'] = 'Mercedes',
		['model'] = 'mb6',
		['price'] = 99999999,
		['category'] = 'vip',
		['hash'] = `mb6`,
		['shop'] = 'luxury',
	},
	['300srt8'] = {
		['name'] = 'Mac 300SRT 8',
		['brand'] = 'Dodge',
		['model'] = '300srt8',
		['price'] = 99999999,
		['category'] = 'vip',
		['hash'] = `300srt8`,
		['shop'] = 'luxury',
	},
	['hellcatw'] = {
		['name'] = 'Mack hellcat',
		['brand'] = 'Dodge',
		['model'] = 'hellcatw',
		['price'] = 99999999,
		['category'] = 'vip',
		['hash'] = `hellcatw`,
		['shop'] = 'luxury',
	},
	['infinitig35'] = {
		['name'] = 'InfinitiG35',
		['brand'] = 'Infiniti',
		['model'] = 'infinitig35',
		['price'] = 20000,
		['category'] = 'infiniti',
		['hash'] = `infinitig35`,
		['shop'] = 'pdm',
	},
	['tazg35'] = {
		['name'] = 'InfinitiG35',
		['brand'] = 'Infiniti',
		['model'] = 'tazg35',
		['price'] = 99999999,
		['category'] = 'vip',
		['hash'] = `tazg35`,
		['shop'] = 'luxury',
	},
	['skylineSC'] = {
		['name'] = 'SkylineSC',
		['brand'] = 'Nissan',
		['model'] = 'skylineSC',
		['price'] = 99999999,
		['category'] = 'vip',
		['hash'] = `skylineSC`,
		['shop'] = 'luxury',
	},
	['73drop'] = {
		['name'] = 'BOE 73Drop',
		['brand'] = 'Chevy',
		['model'] = '73drop',
		['price'] = 99999999,
		['category'] = 'vip',
		['hash'] = `73drop`,
		['shop'] = 'luxury',
	},
	['21ltz'] = {
		['name'] = 'Camaro ZL1',
		['brand'] = 'chevrolet',
		['model'] = '21ltz',
		['price'] = 99999999,
		['category'] = 'vip',
		['hash'] = `21ltz`,
		['shop'] = 'luxury',
	},
	['srtday20'] = {
		['name'] = 'Daytona Charger',
		['brand'] = 'Dodge',
		['model'] = 'srtday20',
		['price'] = 99999999,
		['category'] = 'vip',
		['hash'] = `srtday20`,
		['shop'] = 'luxury',
	},
	['scat'] = {
		['name'] = 'Von Scat',
		['brand'] = 'Dodge',
		['model'] = 'scat',
		['price'] = 99999999,
		['category'] = 'vip',
		['hash'] = `scat`,
		['shop'] = 'luxury',
	},
	['zx10r'] = {
		['name'] = 'Boe Bike',
		['brand'] = 'Suzuki',
		['model'] = 'zx10r',
		['price'] = 99999999,
		['category'] = 'vip',
		['hash'] = `zx10r`,
		['shop'] = 'luxury',
	},
	['73hard'] = {
		['name'] = 'Monsta Car',
		['brand'] = 'Cadillac',
		['model'] = '73hard',
		['price'] = 99999999,
		['category'] = 'vip',
		['hash'] = `73hard`,
		['shop'] = 'luxury',
	},
	['freebochrghoulre'] = {
		['name'] = 'SRT Ghoul',
		['brand'] = 'Dodge',
		['model'] = 'freebochrghoulre',
		['price'] = 99999999,
		['category'] = 'vip',
		['hash'] = `freebochrghoulre`,
		['shop'] = 'luxury',
	},
	['a80'] = {
		['name'] = 'Taz A80',
		['brand'] = 'Toyota',
		['model'] = 'a80',
		['price'] = 99999999,
		['category'] = 'vip',
		['hash'] = `a80`,
		['shop'] = 'luxury',
	},
	['gcmm5cs'] = {
		['name'] = 'M5 CS',
		['brand'] = 'BMW',
		['model'] = 'gcmm5cs',
		['price'] = 99999999,
		['category'] = 'vip',
		['hash'] = `gcmm5cs`,
		['shop'] = 'luxury',
	},
	['supra20'] = {
		['name'] = '2020 Supra',
		['brand'] = 'Toyota',
		['model'] = 'supra20',
		['price'] = 99999999,
		['category'] = 'vip',
		['hash'] = `supra20`,
		['shop'] = 'luxury',
	},
	['camtaz'] = {
		['name'] = 'Taz Cam',
		['brand'] = 'Toyota',
		['model'] = 'camtaz',
		['price'] = 99999999,
		['category'] = 'vip',
		['hash'] = `camtaz`,
		['shop'] = 'luxury',
	},
	['dc5'] = {
		['name'] = 'Taz DC5',
		['brand'] = 'Acura',
		['model'] = 'dc5',
		['price'] = 99999999,
		['category'] = 'vip',
		['hash'] = `dc5`,
		['shop'] = 'luxury',
	},
	['scatpack'] = {
		['name'] = 'Corey Scatpack',
		['brand'] = 'Dodge',
		['model'] = 'scatpack',
		['price'] = 99999999,
		['category'] = 'vip',
		['hash'] = `scatpack`,
		['shop'] = 'luxury',
	},
	['nzp'] = {
		['name'] = 'Nissan Sentra',
		['brand'] = 'Nissan',
		['model'] = 'nzp',
		['price'] = 99999999,
		['category'] = 'vip',
		['hash'] = `nzp`,
		['shop'] = 'luxury',
	},
	['tesroad20'] = {
		['name'] = 'Taz Tesla',
		['brand'] = 'Tesla',
		['model'] = 'tesroad20',
		['price'] = 99999999,
		['category'] = 'vip',
		['hash'] = `tesroad20`,
		['shop'] = 'luxury',
	},
	['tltypes'] = {
		['name'] = 'Acura TL Type-S',
		['brand'] = 'aston',
		['model'] = 'tltypes',
		['price'] = 24000,
		['category'] = 'aston',
		['hash'] = `tltypes`,
		['shop'] = 'pdm',
	},
	['ast'] = {
		['name'] = '2013 Aston Martin Vanquish',
		['brand'] = 'aston',
		['model'] = 'ast',
		['price'] = 24000,
		['category'] = 'aston',
		['hash'] = `ast`,
		['shop'] = 'pdm',
	},
	['amdbx'] = {
		['name'] = 'Aston Martin DBX Carbon Edition',
		['brand'] = 'aston',
		['model'] = 'amdbx',
		['price'] = 24000,
		['category'] = 'aston',
		['hash'] = `amdbx`,
		['shop'] = 'pdm',
	},
	['aaq4'] = {
		['name'] = '2017 Audi A4 Quattro ABT',
		['brand'] = 'audi',
		['model'] = 'aaq4',
		['price'] = 24000,
		['category'] = 'audi',
		['hash'] = `aaq4`,
		['shop'] = 'pdm',
	},
	['q820'] = {
		['name'] = '2020 Audi Q8 50TDI',
		['brand'] = 'audi',
		['model'] = 'q820',
		['price'] = 15000,
		['category'] = 'audi',
		['hash'] = `q820`,
		['shop'] = 'pdm',
	},
	['r8ppi'] = {
		['name'] = '2013 Audi R8 V10',
		['brand'] = 'audi',
		['model'] = 'r8ppi',
		['price'] = 19000,
		['category'] = 'audi',
		['hash'] = `r8ppi`,
		['shop'] = 'pdm',
	},
	['r820'] = {
		['name'] = '2020 Audi R8',
		['brand'] = 'audi',
		['model'] = 'r820',
		['price'] = 55000,
		['category'] = 'audi',
		['hash'] = `r820`,
		['shop'] = 'pdm',
	},
	['sq72016'] = {
		['name'] = '2016 Audi SQ7',
		['brand'] = 'audi',
		['model'] = 'sq72016',
		['price'] = 30000,
		['category'] = 'audi',
		['hash'] = `sq72016`,
		['shop'] = 'pdm',
	},
	['ttrs'] = {
		['name'] = '2010 Audi TT RS',
		['brand'] = 'audi',
		['model'] = 'ttrs',
		['price'] = 125000,
		['category'] = 'audi',
		['hash'] = `ttrs`,
		['shop'] = 'pdm',
	},
	['bbentayga'] = {
		['name'] = 'Bentley Bentayga',
		['brand'] = 'bentley',
		['model'] = 'bbentayga',
		['price'] = 20000,
		['category'] = 'bentley',
		['hash'] = `bbentayga`,
		['shop'] = 'pdm',
	},
	['cgts'] = {
		['name'] = '2020 Bentley Continental GT Convertible',
		['brand'] = 'bentley',
		['model'] = 'cgts',
		['price'] = 30000,
		['category'] = 'bentley',
		['hash'] = `cgts`,
		['shop'] = 'pdm',
	},
	['m3e36'] = {
		['name'] = '1997 BMW M3 E36',
		['brand'] = 'bmw',
		['model'] = 'm3e36',
		['price'] = 18000,
		['category'] = 'bmw',
		['hash'] = `m3e36`,
		['shop'] = 'pdm',
	},
	['bmwx6mham'] = {
		['name'] = 'BMW X6M',
		['brand'] = 'bmw',
		['model'] = 'bmwx6mham',
		['price'] = 20000,
		['category'] = 'vip',
		['hash'] = `bmwx6mham`,
		['shop'] = 'luxury',
	},
	['x5e53'] = {
		['name'] = 'BMW X5 E53 2005 Sport Package',
		['brand'] = 'bmw',
		['model'] = 'x5e53',
		['price'] = 20000,
		['category'] = 'bmw',
		['hash'] = `x5e53`,
		['shop'] = 'pdm',
	},
	--[['i8'] = {
		['name'] = '2015 BMW i8 (I12)',
		['brand'] = 'bmw',
		['model'] = 'i8',
		['price'] = 20000,
		['category'] = 'bmw',
		['hash'] = `i8`,
		['shop'] = 'pdm',
	},]]
	['m3f80'] = {
		['name'] = '2015 BMW M3 (F80)',
		['brand'] = 'bmw',
		['model'] = 'm3f80',
		['price'] = 25000,
		['category'] = 'bmw',
		['hash'] = `m3f80`,
		['shop'] = 'pdm',
	},
	['m4f82'] = {
		['name'] = '2015 BMW M4 F82',
		['brand'] = 'bmw',
		['model'] = 'm4f82',
		['price'] = 11500,
		['category'] = 'bmw',
		['hash'] = `m4f82`,
		['shop'] = 'pdm',
	},
	['m6f13'] = {
		['name'] = 'BMW M6 F13 Shadow Line',
		['brand'] = 'bmw',
		['model'] = 'm6f13',
		['price'] = 16000,
		['category'] = 'bmw',
		['hash'] = `m6f13`,
		['shop'] = 'pdm',
	},
	['z419'] = {
		['name'] = '2019 BMW Z4 M40i',
		['brand'] = 'bmw',
		['model'] = 'z419',
		['price'] = 14000,
		['category'] = 'bmw',
		['hash'] = `z419`,
		['shop'] = 'pdm',
	},
	['bolide'] = {
		['name'] = '2020 Bugatti Bolide',
		['brand'] = 'bugatti',
		['model'] = 'bolide',
		['price'] = 12500,
		['category'] = 'bugatti',
		['hash'] = `bolide`,
		['shop'] = 'pdm',
	},
	['cats'] = {
		['name'] = '2016 Cadillac ATS-V Coupe',
		['brand'] = 'cadillac',
		['model'] = 'cats',
		['price'] = 7200,
		['category'] = 'cadillac',
		['hash'] = `cats`,
		['shop'] = 'pdm',
	},
	['cesc21'] = {
		['name'] = '2021 Cadillac Escalade',
		['brand'] = 'cadillac',
		['model'] = 'cesc21',
		['price'] = 8000,
		['category'] = 'cadillac',
		['hash'] = `cesc21`,
		['shop'] = 'pdm',
	},
	['09tahoe'] = {
		['name'] = '2009 Chevrolet Tahoe',
		['brand'] = 'chevrolet',
		['model'] = '09tahoe',
		['price'] = 18000,
		['category'] = 'chevrolet',
		['hash'] = `09tahoe`,
		['shop'] = 'pdm',
	},
	['15tahoe'] = {
		['name'] = '2015 Chevrolet Tahoe',
		['brand'] = 'chevrolet',
		['model'] = '15tahoe',
		['price'] = 10000,
		['category'] = 'chevrolet',
		['hash'] = `15tahoe`,
		['shop'] = 'pdm',
	},
	['2020ss'] = {
		['name'] = '2020 Chevrolet Camaro SS',
		['brand'] = 'chevrolet',
		['model'] = '2020ss',
		['price'] = 10000,
		['category'] = 'chevrolet',
		['hash'] = `2020ss`,
		['shop'] = 'pdm',
	},
	['camrs17'] = {
		['name'] = '2017 Chevrolet Camaro RS',
		['brand'] = 'chevrolet',
		['model'] = 'camrs17',
		['price'] = 12000,
		['category'] = 'chevrolet',
		['hash'] = `camrs17`,
		['shop'] = 'pdm',
	},
	['tahoe21'] = {
		['name'] = '2021 Chevrolet Tahoe RST',
		['brand'] = 'chevrolet',
		['model'] = 'tahoe21',
		['price'] = 45000,
		['category'] = 'chevrolet',
		['hash'] = `tahoe21`,
		['shop'] = 'pdm',
	},
	--[['corvettec5z06'] = {
		['name'] = 'Chevrolet Corvette C5 Z06',
		['brand'] = 'chevrolet',
		['model'] = 'corvettec5z06',
		['price'] = 32000,
		['category'] = 'chevrolet',
		['hash'] = `corvettec5z06`,
		['shop'] = 'pdm',
	},]]
	['czr1'] = {
		['name'] = '2009 Chevrolet Corvette ZR1',
		['brand'] = 'chevrolet',
		['model'] = 'czr1',
		['price'] = 19000,
		['category'] = 'chevrolet',
		['hash'] = `czr1`,
		['shop'] = 'pdm',
	},
	['c7'] = {
		['name'] = '2014 Chevrolet Corvette C7 Stingray',
		['brand'] = 'chevrolet',
		['model'] = 'c7',
		['price'] = 29000,
		['category'] = 'chevrolet',
		['hash'] = `c7`,
		['shop'] = 'pdm',
	},
	--[['stingray'] = {
		['name'] = 'Dolph C8',
		['brand'] = 'chevrolet',
		['model'] = 'stingray',
		['price'] = 999999999,
		['category'] = 'luxury',
		['hash'] = `stingray`,
		['shop'] = 'luxury',
	},]]
	--[['chr20'] = {
		['name'] = 'Dodge Charger Hellcat Widebody 2021',
		['brand'] = 'dodge',
		['model'] = 'chr20',
		['price'] = 13000,
		['category'] = 'dodge',
		['hash'] = `chr20`,
		['shop'] = 'pdm',
	},]]
	['demon'] = {
		['name'] = '2018 Dodge Challenger SRT Demon',
		['brand'] = 'dodge',
		['model'] = 'demon',
		['price'] = 18000,
		['category'] = 'dodge',
		['hash'] = `demon`,
		['shop'] = 'pdm',
	},
	['ram2500'] = {
		['name'] = '2015 Dodge RAM 2500',
		['brand'] = 'dodge',
		['model'] = 'ram2500',
		['price'] = 19000,
		['category'] = 'dodge',
		['hash'] = `ram2500`,
		['shop'] = 'pdm',
	},
	['srt4'] = {
		['name'] = 'Dodge Neon SRT-4',
		['brand'] = 'dodge',
		['model'] = 'srt4',
		['price'] = 15000,
		['category'] = 'dodge',
		['hash'] = `srt4`,
		['shop'] = 'pdm',
	},
	['trx'] = {
		['name'] = '2017 Dodge RAM 1500 Rebel TRX',
		['brand'] = 'dodge',
		['model'] = 'trx',
		['price'] = 19500,
		['category'] = 'dodge',
		['hash'] = `trx`,
		['shop'] = 'pdm',
	},
	['488'] = {
		['name'] = 'Ferrari 488 Spider',
		['brand'] = 'ferrari',
		['model'] = '488',
		['price'] = 10800,
		['category'] = 'ferrari',
		['hash'] = `488`,
		['shop'] = 'pdm',
	},
	--[['f812'] = {
		['name'] = '2018 Ferrari 812 Superfast',
		['brand'] = 'ferrari',
		['model'] = 'f812',
		['price'] = 5500,
		['category'] = 'ferrari',
		['hash'] = `f812`,
		['shop'] = 'pdm',
	},]]
	--[['fct'] = {
		['name'] = '2015 Ferrari California T',
		['brand'] = 'ferrari',
		['model'] = 'fct',
		['price'] = 55000,
		['category'] = 'ferrari',
		['hash'] = `fct`,
		['shop'] = 'pdm',
	},]]
	['fxxk'] = {
		['name'] = 'Ferrari FXX-K Hybrid Hypercar',
		['brand'] = 'ferrari',
		['model'] = 'fxxk',
		['price'] = 8500,
		['category'] = 'ferrari',
		['hash'] = `fxxk`,
		['shop'] = 'pdm',
	},
	['laferrari'] = {
		['name'] = '2015 Ferrari LaFerrari',
		['brand'] = 'ferrari',
		['model'] = 'laferrari',
		['price'] = 12000,
		['category'] = 'ferrari',
		['hash'] = `laferrari`,
		['shop'] = 'pdm',
	},
	--[['mig'] = {
		['name'] = 'Ferrari Enzo',
		['brand'] = 'ferrari',
		['model'] = 'mig',
		['price'] = 6500,
		['category'] = 'ferrari',
		['hash'] = `mig`,
		['shop'] = 'pdm',
	},]]
	--[['yFe458i2'] = {
		['name'] = '458 Speciale',
		['brand'] = 'ferrari',
		['model'] = 'yFe458i2',
		['price'] = 8000,
		['category'] = 'ferrari',
		['hash'] = `yFe458i2`,
		['shop'] = 'pdm',
	},]]
	--[['yFe458s1'] = {
		['name'] = '458 Spider',
		['brand'] = 'ferrari',
		['model'] = 'yFe458s1',
		['price'] = 14000,
		['category'] = 'ferrari',
		['hash'] = `yFe458s1`,
		['shop'] = 'pdm',
	},]]
	--[['yFe458s2'] = {
		['name'] = '458 Speciale Aperta',
		['brand'] = 'ferrari',
		['model'] = 'yFe458s2',
		['price'] = 5000,
		['category'] = 'ferrari',
		['hash'] = `yFe458s2`,
		['shop'] = 'pdm',
	},]]
	--[['yFeF12A'] = {
		['name'] = 'Ferrari F60 America',
		['brand'] = 'ferrari',
		['model'] = 'yFeF12A',
		['price'] = 25000,
		['category'] = 'ferrari',
		['hash'] = `yFeF12A`,
		['shop'] = 'pdm',
	},]]
	--[['yFeF12T'] = {
		['name'] = 'Ferrari F12 TRS Roadster',
		['brand'] = 'ferrari',
		['model'] = 'yFeF12T',
		['price'] = 90000,
		['category'] = 'ferrari',
		['hash'] = `yFeF12T`,
		['shop'] = 'pdm',
	},]]
	['f150'] = {
		['name'] = '2012 Ford F150 SVT Raptor R',
		['brand'] = 'ford',
		['model'] = 'f150',
		['price'] = 130000,
		['category'] = 'ford',
		['hash'] = `f150`,
		['shop'] = 'pdm',
	},
	['gt17'] = {
		['name'] = '2017 Ford GT',
		['brand'] = 'ford',
		['model'] = 'gt17',
		['price'] = 4000,
		['category'] = 'ford',
		['hash'] = `gt17`,
		['shop'] = 'pdm',
	},
	['wildtrak'] = {
		['name'] = '2021 Ford Bronco Wildtrak',
		['brand'] = 'ford',
		['model'] = 'wildtrak',
		['price'] = 60000,
		['category'] = 'ford',
		['hash'] = `wildtrak`,
		['shop'] = 'pdm',
	},
	['na1'] = {
		['name'] = '1992 Honda NSX-R (NA1)',
		['brand'] = 'honda',
		['model'] = 'na1',
		['price'] = 70000,
		['category'] = 'honda',
		['hash'] = `na1`,
		['shop'] = 'pdm',
	},
	['it18'] = {
		['name'] = '2017 Italdesign Zerouno',
		['brand'] = 'italdesign',
		['model'] = 'it18',
		['price'] = 17000,
		['category'] = 'italdesign',
		['hash'] = `it18`,
		['shop'] = 'pdm',
	},
	['srt8'] = {
		['name'] = '2015 Jeep SRT-8',
		['brand'] = 'jeep',
		['model'] = 'srt8',
		['price'] = 35000,
		['category'] = 'jeep',
		['hash'] = `srt8`,
		['shop'] = 'pdm',
	},
	['trhawk'] = {
		['name'] = '2018 Jeep Grand Cherokee',
		['brand'] = 'jeep',
		['model'] = 'trhawk',
		['price'] = 16000,
		['category'] = 'jeep',
		['hash'] = `trhawk`,
		['shop'] = 'pdm',
	},
	['agerars'] = {
		['name'] = '2017 Koenigsegg Agera RS',
		['brand'] = 'koenigsegg',
		['model'] = 'agerars',
		['price'] = 40000,
		['category'] = 'koenigsegg',
		['hash'] = `agerars`,
		['shop'] = 'pdm',
	},
	['regera'] = {
		['name'] = 'Koenigsegg Regera',
		['brand'] = 'koenigsegg',
		['model'] = 'regera',
		['price'] = 55000,
		['category'] = 'koenigsegg',
		['hash'] = `regera`,
		['shop'] = 'pdm',
	},
	['lambose'] = {
		['name'] = 'Lamborghini Sesto Elemento',
		['brand'] = 'lamborghini',
		['model'] = 'lambose',
		['price'] = 45000,
		['category'] = 'lamborghini',
		['hash'] = `lambose`,
		['shop'] = 'pdm',
	},
	['lp670sv'] = {
		['name'] = '2009 Lamborghini Murcielago LP 670-4 SV',
		['brand'] = 'lamborghini',
		['model'] = 'lp670sv',
		['price'] = 25000,
		['category'] = 'lamborghini',
		['hash'] = `lp670sv`,
		['shop'] = 'pdm',
	},
	['lp700r'] = {
		['name'] = '2013 Lamborghini Aventador LP700-4 Roadster',
		['brand'] = 'lamborghini',
		['model'] = 'lp700r',
		['price'] = 32000,
		['category'] = 'lamborghini',
		['hash'] = `lp700r`,
		['shop'] = 'pdm',
	},
	['svj63'] = {
		['name'] = 'Lamborghini Aventador SVJ',
		['brand'] = 'lamborghini',
		['model'] = 'svj63',
		['price'] = 62000,
		['category'] = 'lamborghini',
		['hash'] = `svj63`,
		['shop'] = 'pdm',
	},
	['urus'] = {
		['name'] = 'Lamborghini Urus',
		['brand'] = 'lamborghini',
		['model'] = 'urus',
		['price'] = 85000,
		['category'] = 'lamborghini',
		['hash'] = `urus`,
		['shop'] = 'pdm',
	},
	['veneno'] = {
		['name'] = 'Lamborghini Veneno',
		['brand'] = 'lamborghini',
		['model'] = 'veneno',
		['price'] = 155000,
		['category'] = 'lamborghini',
		['hash'] = `veneno`,
		['shop'] = 'pdm',
	},
	['is350mod'] = {
		['name'] = '2014 Lexus IS 350',
		['brand'] = 'lexus',
		['model'] = 'is350mod',
		['price'] = 40000,
		['category'] = 'lexus',
		['hash'] = `is350mod`,
		['shop'] = 'pdm',
	},
	['rcf'] = {
		['name'] = '2015 Lexus RCF',
		['brand'] = 'lexus',
		['model'] = 'rcf',
		['price'] = 12800,
		['category'] = 'lexus',
		['hash'] = `rcf`,
		['shop'] = 'pdm',
	},
	['levante'] = {
		['name'] = 'Maserati Levante',
		['brand'] = 'maserati',
		['model'] = 'levante',
		['price'] = 75000,
		['category'] = 'maserati',
		['hash'] = `levante`,
		['shop'] = 'pdm',
	},
	['fc3s'] = {
		['name'] = 'Mazda RX7 FC3S',
		['brand'] = 'mazda',
		['model'] = 'fc3s',
		['price'] = 12000,
		['category'] = 'mazda',
		['hash'] = `fc3s`,
		['shop'] = 'pdm',
	},
	['majfd'] = {
		['name'] = 'Mazda RX-7 FD',
		['brand'] = 'mazda',
		['model'] = 'majfd',
		['price'] = 16000,
		['category'] = 'mazda',
		['hash'] = `majfd`,
		['shop'] = 'pdm',
	},
	['miata3'] = {
		['name'] = '1989 Mazda Miata NA',
		['brand'] = 'mazda',
		['model'] = 'miata3',
		['price'] = 6500,
		['category'] = 'mazda',
		['hash'] = `miata3`,
		['shop'] = 'pdm',
	},
	['na6'] = {
		['name'] = 'Mazda MX-5 Miata (NA6C)',
		['brand'] = 'mazda',
		['model'] = 'na6',
		['price'] = 8500,
		['category'] = 'mazda',
		['hash'] = `na6`,
		['shop'] = 'pdm',
	},
	['650s'] = {
		['name'] = 'McLaren 650S Coupe',
		['brand'] = 'mclaren',
		['model'] = '650s',
		['price'] = 45000,
		['category'] = 'mclaren',
		['hash'] = `650s`,
		['shop'] = 'pdm',
	},
	['675lt'] = {
		['name'] = '2016 McLaren 675LT Coupe',
		['brand'] = 'mclaren',
		['model'] = '675lt',
		['price'] = 120000,
		['category'] = 'mclaren',
		['hash'] = `675lt`,
		['shop'] = 'pdm',
	},
	['720s'] = {
		['name'] = '2017 McLaren 720S',
		['brand'] = 'mclaren',
		['model'] = '720s',
		['price'] = 8000,
		['category'] = 'mclaren',
		['hash'] = `720s`,
		['shop'] = 'pdm',
	},
	['gtr96'] = {
		['name'] = '1996 McLaren F1 GTR',
		['brand'] = 'mclaren',
		['model'] = 'gtr96',
		['price'] = 45000,
		['category'] = 'mclaren',
		['hash'] = `gtr96`,
		['shop'] = 'pdm',
	},
	--[['mp412c'] = {
		['name'] = 'McLaren MP4-12C',
		['brand'] = 'mclaren',
		['model'] = 'mp412c',
		['price'] = 55000,
		['category'] = 'mclaren',
		['hash'] = `mp412c`,
		['shop'] = 'pdm',
	},]]
	['senna'] = {
		['name'] = '2019 McLaren Senna',
		['brand'] = 'mclaren',
		['model'] = 'senna',
		['price'] = 210000,
		['category'] = 'mclaren',
		['hash'] = `senna`,
		['shop'] = 'pdm',
	},
	['amggtrr20'] = {
		['name'] = '2020 Mercedes-Benz AMG GT-R Roadster',
		['brand'] = 'mercedesbenz',
		['model'] = 'amggtrr20',
		['price'] = 60000,
		['category'] = 'mercedes',
		['hash'] = `amggtrr20`,
		['shop'] = 'pdm',
	},
	['c6320'] = {
		['name'] = '2020 Mercedes-AMG C63s',
		['brand'] = 'mercedesamg',
		['model'] = 'c6320',
		['price'] = 80000,
		['category'] = 'mercedes',
		['hash'] = `c6320`,
		['shop'] = 'pdm',
	},
	['G65'] = {
		['name'] = '2013 Mercedes-Benz G65 AMG',
		['brand'] = 'mercedesbenz',
		['model'] = 'G65',
		['price'] = 55000,
		['category'] = 'mercedes',
		['hash'] = `G65`,
		['shop'] = 'pdm',
	},
	['e400'] = {
		['name'] = '2019 Mercedes-Benz E400 Coupe 4matic (C238)',
		['brand'] = 'mercedesbenz',
		['model'] = 'e400',
		['price'] = 32000,
		['category'] = 'mercedes',
		['hash'] = `e400`,
		['shop'] = 'pdm',
	},
	['mbc63'] = {
		['name'] = '2012 Mercedes-Benz C63 AMG Coupe Black Series',
		['brand'] = 'mercedesbenz',
		['model'] = 'mbc63',
		['price'] = 42000,
		['category'] = 'mercedes',
		['hash'] = `mbc63`,
		['shop'] = 'pdm',
	},
	['s500w222'] = {
		['name'] = '2014 Mercedes-Benz S500 W222',
		['brand'] = 'mercedesbenz',
		['model'] = 's500w222',
		['price'] = 55000,
		['category'] = 'mercedes',
		['hash'] = `s500w222`,
		['shop'] = 'pdm',
	},
	['sl500'] = {
		['name'] = '1995 Mercedes-Benz SL500',
		['brand'] = 'mercedesbenz',
		['model'] = 'sl500',
		['price'] = 38000,
		['category'] = 'mercedes',
		['hash'] = `sl500`,
		['shop'] = 'pdm',
	},
	['v250'] = {
		['name'] = 'Mercedes-Benz V-class 250 Bluetec LWB',
		['brand'] = 'mercedesbenz',
		['model'] = 'v250',
		['price'] = 35000,
		['category'] = 'mercedes',
		['hash'] = `v250`,
		['shop'] = 'pdm',
	},
	['fto'] = {
		['name'] = 'Mitsubishi FTO GP Version-R',
		['brand'] = 'mitsubishi',
		['model'] = 'fto',
		['price'] = 40000,
		['category'] = 'mitsubishi',
		['hash'] = `fto`,
		['shop'] = 'pdm',
	},
	['maj350'] = {
		['name'] = 'Nissan Fairlady Z Z33',
		['brand'] = 'nissan',
		['model'] = 'maj350',
		['price'] = 45000,
		['category'] = 'nissan',
		['hash'] = `maj350`,
		['shop'] = 'pdm',
	},
	['nzp'] = {
		['name'] = 'Nissan 370z Pandem',
		['brand'] = 'nissan',
		['model'] = 'nzp',
		['price'] = 70000,
		['category'] = 'nissan',
		['hash'] = `nzp`,
		['shop'] = 'pdm',
	},
	['s14'] = {
		['name'] = '1998 Nissan Silvia K',
		['brand'] = 'nissan',
		['model'] = 's14',
		['price'] = 55000,
		['category'] = 'nissan',
		['hash'] = `s14`,
		['shop'] = 'pdm',
	},
	['maj935'] = {
		['name'] = '1978 Porsche 935 Moby Dick',
		['brand'] = 'porsche',
		['model'] = 'maj935',
		['price'] = 65000,
		['category'] = 'porsche',
		['hash'] = `maj935`,
		['shop'] = 'pdm',
	},
	['pcs18'] = {
		['name'] = '2018 Porsche Cayenne S',
		['brand'] = 'porsche',
		['model'] = 'pcs18',
		['price'] = 65000,
		['category'] = 'porsche',
		['hash'] = `pcs18`,
		['shop'] = 'pdm',
	},
	['718caymans'] = {
		['name'] = 'Porsche 718 Cayman S',
		['brand'] = 'porsche',
		['model'] = '718caymans',
		['price'] = 80000,
		['category'] = 'porsche',
		['hash'] = `718caymans`,
		['shop'] = 'pdm',
	},
	['cgt'] = {
		['name'] = '2003 Porsche Carrera GT (980)',
		['brand'] = 'porsche',
		['model'] = 'cgt',
		['price'] = 38500,
		['category'] = 'porsche',
		['hash'] = `cgt`,
		['shop'] = 'pdm',
	},
	['pm19'] = {
		['name'] = '2019 Porsche Macan Turbo',
		['brand'] = 'porsche',
		['model'] = 'pm19',
		['price'] = 55000,
		['category'] = 'porsche',
		['hash'] = `pm19`,
		['shop'] = 'pdm',
	},
	['taycan'] = {
		['name'] = '2020 Porsche Taycan Turbo S',
		['brand'] = 'porsche',
		['model'] = 'taycan',
		['price'] = 45000,
		['category'] = 'porsche',
		['hash'] = `taycan`,
		['shop'] = 'pdm',
	},
	--[['yPG205t16B'] = {
		['name'] = 'Peugeot 205 Turbo 16',
		['brand'] = 'peugeot',
		['model'] = 'yPG205t16B',
		['price'] = 45000,
		['category'] = 'peugeot',
		['hash'] = `yPG205t16B`,
		['shop'] = 'pdm',
	},]]
	--[['yPG205t16A'] = {
		['name'] = 'Peugeot 205 Rally',
		['brand'] = 'peugeot',
		['model'] = 'yPG205t16A',
		['price'] = 45000,
		['category'] = 'peugeot',
		['hash'] = `yPG205t16A`,
		['shop'] = 'pdm',
	},]]
	['rrevoque'] = {
		['name'] = 'Range Rover Evoque',
		['brand'] = 'rangerover',
		['model'] = 'rrevoque',
		['price'] = 40000,
		['category'] = 'rangerover',
		['hash'] = `rrevoque`,
		['shop'] = 'pdm',
	},
	--[['rrst'] = {
		['name'] = 'Range Rover Vogue Startech',
		['brand'] = 'rangerover',
		['model'] = 'rrst',
		['price'] = 65000,
		['category'] = 'rangerover',
		['hash'] = `rrst`,
		['shop'] = 'pdm',
	},]]
	['rsvr16'] = {
		['name'] = '2016 Range Rover Sport SVR',
		['brand'] = 'rangerover',
		['model'] = 'rsvr16',
		['price'] = 135000,
		['category'] = 'rangerover',
		['hash'] = `rsvr16`,
		['shop'] = 'pdm',
	},
	['dawnonyx'] = {
		['name'] = '2016 Rolls-Royce Dawn Onyx',
		['brand'] = 'rollsroyce',
		['model'] = 'dawnonyx',
		['price'] = 38000,
		['category'] = 'rollsroyce',
		['hash'] = `dawnonyx`,
		['shop'] = 'pdm',
	},
	['wraith'] = {
		['name'] = 'Rolls-Royce Wraith',
		['brand'] = 'rollsroyce',
		['model'] = 'wraith',
		['price'] = 30000,
		['category'] = 'rollsroyce',
		['hash'] = `wraith`,
		['shop'] = 'pdm',
	},
	['rculi'] = {
		['name'] = 'Taz Rolls Royce Cullinan',
		['brand'] = 'rollsroyce',
		['model'] = 'rculi',
		['price'] = 9999999,
		['category'] = 'vip',
		['hash'] = `rculi`,
		['shop'] = 'luxury',
	},
	['rrphantom'] = {
		['name'] = '2018 Rolls-Royce Phantom VIII',
		['brand'] = 'rollsroyce',
		['model'] = 'rrphantom',
		['price'] = 70000,
		['category'] = 'rollsroyce',
		['hash'] = `rrphantom`,
		['shop'] = 'pdm',
	},
	['subisti08'] = {
		['name'] = '2008 Subaru WRX STi',
		['brand'] = 'subaru',
		['model'] = 'subisti08',
		['price'] = 65000,
		['category'] = 'subaru',
		['hash'] = `subisti08`,
		['shop'] = 'pdm',
	},
	['subwrx'] = {
		['name'] = '2004 Subaru Impreza WRX STI',
		['brand'] = 'subaru',
		['model'] = 'subwrx',
		['price'] = 130000,
		['category'] = 'subaru',
		['hash'] = `subwrx`,
		['shop'] = 'pdm',
	},
	['svx'] = {
		['name'] = '1996 Subaru Alcyone SVX',
		['brand'] = 'subaru',
		['model'] = 'svx',
		['price'] = 35000,
		['category'] = 'subaru',
		['hash'] = `svx`,
		['shop'] = 'pdm',
	},
	--[['gsxr19'] = {
		['name'] = '2019 Suzuki GSX-R1000R',
		['brand'] = 'suzuki',
		['model'] = 'gsxr19',
		['price'] = 28000,
		['category'] = 'suzuki',
		['hash'] = `gsxr19`,
		['shop'] = 'pdm',
	},]]
	['katana'] = {
		['name'] = '2019 Suzuki Katana',
		['brand'] = 'suzuki',
		['model'] = 'katana',
		['price'] = 35000,
		['category'] = 'suzuki',
		['hash'] = `katana`,
		['shop'] = 'pdm',
	},
	['tr22'] = {
		['name'] = '2020 Tesla Roadster',
		['brand'] = 'tesla',
		['model'] = 'tr22',
		['price'] = 45000,
		['category'] = 'tesla',
		['hash'] = `tr22`,
		['shop'] = 'pdm',
	},
	['p90d'] = {
		['name'] = 'Tesla Model X Performance',
		['brand'] = 'tesla',
		['model'] = 'p90d',
		['price'] = 50000,
		['category'] = 'tesla',
		['hash'] = `p90d`,
		['shop'] = 'pdm',
	},
	['models'] = {
		['name'] = '2016 Tesla Model S P90D',
		['brand'] = 'tesla',
		['model'] = 'models',
		['price'] = 39500,
		['category'] = 'tesla',
		['hash'] = `models`,
		['shop'] = 'pdm',
	},
	['tmodel'] = {
		['name'] = '2018 Tesla Model 3',
		['brand'] = 'tesla',
		['model'] = 'tmodel',
		['price'] = 15000,
		['category'] = 'tesla',
		['hash'] = `tmodel`,
		['shop'] = 'pdm',
	},
	['teslax'] = {
		['name'] = '2016 Tesla Model X P90D',
		['brand'] = 'tesla',
		['model'] = 'teslax',
		['price'] = 50000,
		['category'] = 'tesla',
		['hash'] = `teslax`,
		['shop'] = 'pdm',
	},
	['teslapd'] = {
		['name'] = '2017 Tesla Model S',
		['brand'] = 'tesla',
		['model'] = 'teslapd',
		['price'] = 40000,
		['category'] = 'tesla',
		['hash'] = `teslapd`,
		['shop'] = 'pdm',
	},
	['cam8tun'] = {
		['name'] = '2018 Toyota Camry XSE',
		['brand'] = 'toyota',
		['model'] = 'cam8tun',
		['price'] = 70000,
		['category'] = 'toyota',
		['hash'] = `cam8tun`,
		['shop'] = 'pdm',
	},
	['vxr'] = {
		['name'] = '2016 Toyota Land Cruiser VXR',
		['brand'] = 'toyota',
		['model'] = 'vxr',
		['price'] = 900000,
		['category'] = 'toyota',
		['hash'] = `vxr`,
		['shop'] = 'pdm',
	},
	['toysupmk4'] = {
		['name'] = '1998 Toyota Supra Turbo (A80)',
		['brand'] = 'toyota',
		['model'] = 'toysupmk4',
		['price'] = 255000,
		['category'] = 'toyota',
		['hash'] = `toysupmk4`,
		['shop'] = 'pdm',
	},
	['mk2100'] = {
		['name'] = 'Toyota Mark II JZX100',
		['brand'] = 'toyota',
		['model'] = 'mk2100',
		['price'] = 90000,
		['category'] = 'toyota',
		['hash'] = `mk2100`,
		['shop'] = 'pdm',
	},
	['golfgti7'] = {
		['name'] = '2015 Volkswagen Golf GTI MK7',
		['brand'] = 'volkswagen',
		['model'] = 'golfgti7',
		['price'] = 375000,
		['category'] = 'volkswagen',
		['hash'] = `golfgti7`,
		['shop'] = 'pdm',
	},
	['passat'] = {
		['name'] = '2016 Volkswagen Passat B8',
		['brand'] = 'volkswagen',
		['model'] = 'passat',
		['price'] = 375000,
		['category'] = 'volkswagen',
		['hash'] = `passat`,
		['shop'] = 'pdm',
	},
	--[['vwr'] = {
		['name'] = 'Volkswagen Scirocco R 2011',
		['brand'] = 'volkswagen',
		['model'] = 'vwr',
		['price'] = 375000,
		['category'] = 'volkswagen',
		['hash'] = `vwr`,
		['shop'] = 'pdm',
	},]]
	['amarok'] = {
		['name'] = '2018 Volkswagen Amarok V6',
		['brand'] = 'volkswagen',
		['model'] = 'amarok',
		['price'] = 375000,
		['category'] = 'volkswagen',
		['hash'] = `amarok`,
		['shop'] = 'pdm',
	},
	['xc90'] = {
		['name'] = 'Volvo XC90 T8',
		['brand'] = 'volvo',
		['model'] = 'xc90',
		['price'] = 425000,
		['category'] = 'volvo',
		['hash'] = `xc90`,
		['shop'] = 'pdm',
	},
	['wmfenyr'] = {
		['name'] = 'W-Motors Fenyr Supersport',
		['brand'] = 'wmotors',
		['model'] = 'wmfenyr',
		['price'] = 220000,
		['category'] = 'wmotors',
		['hash'] = `wmfenyr`,
		['shop'] = 'pdm',
	},
	['lykan'] = {
		['name'] = 'W-Motors Lykan HyperSport',
		['brand'] = 'wmotors',
		['model'] = 'lykan',
		['price'] = 185000,
		['category'] = 'wmotors',
		['hash'] = `lykan`,
		['shop'] = 'pdm',
	},
	--[['21scatdurango'] = { 					------Carset 1
		['name'] = '2021 392 Durango',
		['brand'] = 'Dodge',
		['model'] = '21scatdurango',
		['price'] = 99999999,
		['category'] = 'vip',
		['hash'] = `21scatdurango`,
		['shop'] = 'luxury',
	},]]
	['22demon'] = {
		['name'] = '2022 Demon',
		['brand'] = 'Dodge',
		['model'] = '22demon',
		['price'] = 99999999,
		['category'] = 'vip',
		['hash'] = `22demon`,
		['shop'] = 'luxury',
	},
	['180sx'] = {
		['name'] = 'Nissan 180sx',
		['brand'] = 'Nissan',
		['model'] = '180sx',
		['price'] = 20000,
		['category'] = 'nissan',
		['hash'] = `180sx`,
		['shop'] = 'pdm',
	},
	['300sdemon'] = {
		['name'] = '300s Demon',
		['brand'] = 'Dodge',
		['model'] = '300sdemon',
		['price'] = 99999999,
		['category'] = 'vip',
		['hash'] = `300sdemon`,
		['shop'] = 'luxury',
	},
	['350z'] = {
		['name'] = 'Nissan 350z',
		['brand'] = 'Nissan',
		['model'] = '350z',
		['price'] = 20000,
		['category'] = 'nissan',
		['hash'] = `350z`,
		['shop'] = 'pdm',
	},
	['ap2'] = { 
		['name'] = 'Honda S2000',
		['brand'] = 'Honda',
		['model'] = 'ap2',
		['price'] = 30000,
		['category'] = 'honda',
		['hash'] = `ap2`,
		['shop'] = 'pdm',
	},
	['audis32'] = {
		['name'] = 'Audi S32',
		['brand'] = 'Audi',
		['model'] = 'audis32',
		['price'] = 25000,
		['category'] = 'audi',
		['hash'] = `audis32`,
		['shop'] = 'pdm',
	},
	['benzsl63'] = {
		['name'] = 'AMG SL63',
		['brand'] = 'Mercedes',
		['model'] = 'benzsl63',
		['price'] = 25000,
		['category'] = 'mercedes',
		['hash'] = `benzsl63`,
		['shop'] = 'pdm',
	},
	--[['bmws'] = { --needs fix
		['name'] = 'RR BMWS',
		['brand'] = 'RR',
		['model'] = 'bmws',
		['price'] = 25000,
		['category'] = 'honda',
		['hash'] = `bmws`,
		['shop'] = 'pdm',
	},]]
}
